name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count commits for versioning

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/release.jks

      - name: Create key.properties
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          echo "$KEY_PROPERTIES" > android/key.properties
      
      - name: Get version name
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "VERSION_NAME=1.0.$COMMIT_COUNT" >> $GITHUB_ENV
          echo "VERSION_CODE=$COMMIT_COUNT" >> $GITHUB_ENV

      - name: Build APK
        run: |
          flutter build apk --release \
            --build-name=${{ env.VERSION_NAME }} \
            --build-number=${{ env.VERSION_CODE }}

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/apkgemin-notes-${{ env.VERSION_NAME }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          name: Release v${{ env.VERSION_NAME }}
          body: |
            Automated release for commit ${{ github.sha }}.
            Version: ${{ env.VERSION_NAME }} (Build ${{ env.VERSION_CODE }})
          files: build/app/outputs/flutter-apk/apkgemin-notes-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
